version: "3"
services:
  app:
    image: chui9591/travel_agency:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: travel_agency/custom_db:latest
    ports:
      - "8081:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
    driver: local
